### ISSUE TITLE
Re-usable items consumed in crafting (Excess inventory not working)

### ISSUE THREAD

**Issue by Emperorraccoon** [TeamDman/SuperFactoryManager#10]
As the title says, i am currently attempting to auto craft "Mochi" from pam's. after the mochi is crafted both the bucket and the mortar and pestle dissapear, they do not appear in the specified excess inventory (A vanilla chest).  Trying to output them does not work either.

**Comment by enderger** [comment]
Does this apply to fluid-filled bucket recipes?

**Comment by Emperorraccoon** [comment]
Yes, A water bucket is used in the recipe and is then not returned, however the mortart and pestle is not returned either

**Comment by TeamDman** [comment]
Probably related to an issue I had crafting cactus juice earlier, some internal error caused forge to delete the block rather than crashing the server.
