### ISSUE TITLE
Round Robin implementation

### ISSUE THREAD

**Issue by ilya-pirogov** [TeamDman/SuperFactoryManager#102]
How I can do round robin distribution? I understand that I can write something like:
```
every 20 ticks do
    INPUT stone FROM in
    OUTPUT 10 TO EACH out
end
```
But if "in" is receiving less than 10*out items per second then all items goes into the first "out" only.

**Comment by TeamDman** [comment]
not yet implemented, but if you want to avoid stuffing one inventory when others are empty try

```sfm
every 20 ticks do
  input stone from in
  output retain 1 to each out
end
```

which should ensure each inventory keeps at most 1 stone

**Comment by TeamDman** [comment]
added in 4.14.0, see example programs for usage
