### ISSUE TITLE
Cant label anything with Labelgun

### ISSUE THREAD

**Issue by HabeMichVerirrt** [TeamDman/SuperFactoryManager#104]
After around 130 Labels for other Programs that running well, i was on to build a third setup with SFM for Smelting, but the with Lablel gun i cant label anything at all. Restart Server, restart Game, got new Label gun nothing will help. idk if that bug is known, maybe someone can help me with that issue.

**Comment by TeamDman** [comment]
I think this was a problem in a release that has since been fixed. If still happening can reopen
