### ISSUE TITLE
Minimum trigger interval is 1 second.

### ISSUE THREAD

**Issue by F0x06** [TeamDman/SuperFactoryManager#106]
Hi,

First of all this mod is truely amazing ! Happy that i found it !

While struggling with endgame mekanism reactors, i was curious to try with your mod that supports mekanism gases, however due to verry large steam output (millions mb/t), the minimum trigger interval  for 1 second (20 ticks) can cause issues, is it possible to make this value configurable ? as a workaround i'm using a `Timer` from `RFToolsUtility` configured to 1 tick paired with `EVERY REDSTONE PULSE DO`

Thanks in advance,
F0x.

**Comment by TeamDman** [comment]
It's been default of 1 second just because that's how it has always been, but a config definitely makes sense. Will add to the todo list

**Comment by TeamDman** [comment]
There is a config option for this as of 4.15.0, check out the [changelog video](https://youtu.be/yW9Ij8x6KxQ) to learn more
