### ISSUE TITLE
Suggestion: A NOT option rather than selecting what's allowed

### ISSUE THREAD

**Issue by FHoulbreque** [TeamDman/SuperFactoryManager#109]
Maybe I did miss it but a `not` keyword to blacklist keywords would be really neat. If I missed it, feel free to tell me. Thanks for this awesome updating of this mod I discovered recently in GT:NH (it's original version at least).

**Comment by TeamDman** [comment]
There is an `EXCEPT` keyword which might be what you're looking for

https://github.com/TeamDman/SuperFactoryManager/blob/0b40867422f4c61d182a3202443180c44b0af30a/src/main/resources/assets/sfm/template_programs/filtering.sfml#L23-L28

**Comment by FHoulbreque** [comment]
Oh yes! I missed this one, thank you it's exactly what I was looking for.  And thanks for the awesome reactivity.
