### ISSUE TITLE
Suggestion: allow fluid operations to specify a specific tank

### ISSUE THREAD

**Issue by ab9rf** [TeamDman/SuperFactoryManager#11]
Many machines have multiple tanks, which are identified by numbers the same way that item inventories are identified by slots. It would be useful if the advanced mode for fluid operations would allow the specification of a specific tank or tanks in the same way that item operations can specify a slot or slots to be used.

**Comment by HenryLoenwind** [comment]
While the fluid API lets you query a list of tanks, neither fill nor drain methods take a "tank number" parameter. You only can specify which fluid you want to get or fill in.

**Comment by TeamDman** [comment]
Henry seems to have summed it up pretty well, filtering by fluid type is already in and should be enough to imitate this behaviour.
