### ISSUE TITLE
[1.20.1] Quitting world doesn't save and world gets rolled back. (ca.teamdman.sfm.common.handler.FallingAnvilHandler.onLeave)

### ISSUE THREAD

**Issue by Gbergz** [TeamDman/SuperFactoryManager#114]
### What happened?
This issue seems to be rather rare, but it can happen and cause damage.

### Info: 
Logs tells me something about a FallingAnvilHandler.onLeave.
You can find the logs here: (at the bottom).
https://gist.githubusercontent.com/Gbergz/874f26418760fc77767c3dcd316c6e22/raw/e7c1a8f7006c6af667f57e15f7460f082c81135d/gistfile1.txt

### Versions:
Minecraft: 1.20.1 
Forge: 47.2.17
SFM: 4.14.1

**-** Gbergz

**Comment by TeamDman** [comment]
https://github.com/TeamDman/SuperFactoryManager/blob/a4d675199c0c99d2bb592fcdf1760989a7be7884/src/main/java/ca/teamdman/sfm/common/handler/FallingAnvilHandler.java#L37

Not sure why getting the block state is causing a panic, I recommend avoiding shutting down while anvils are flying✈️ until a proper fix can be implemented

**Comment by Gbergz** [comment]
Yeah I am gonna guess it was an anvil in a structure destroyed by something in the distance causing it to fall then unloaded while falling?, tried 10 worlds after and it didn't happen once 

Atleast it's rare.

**Comment by Gbergz** [comment]
Any updates on this issue? Just had it happen again:
<https://gist.githubusercontent.com/Gbergz/c7d1541f5a6bc1398cbaf532af0042a5/raw/948c748334906f521f96667f630d1b0ac4f24889/gistfile1.txt>

**Comment by TeamDman** [comment]
This should be fixed in as of 4.15.0
