### ISSUE TITLE
1.20.4 Index out of bounds crash

### ISSUE THREAD

**Issue by HappyMolly** [TeamDman/SuperFactoryManager#116]
Hello. 

I used the simple example program, labelled Easy villagers farm blocks "A" and Minecraft Composters "B", when I pushed labels to manager, I got this crash.

[crash-2024-04-18_21.06.28-server.txt](https://github.com/TeamDman/SuperFactoryManager/files/15029587/crash-2024-04-18_21.06.28-server.txt)

**Comment by TeamDman** [comment]
![image](https://github.com/TeamDman/SuperFactoryManager/assets/9356891/c8ffa6c7-42f0-4dea-bdcd-1adea0743dc9)
![image](https://github.com/TeamDman/SuperFactoryManager/assets/9356891/7c43a45f-0f49-4453-9ca3-85c654eda155)

I am able to reproduce, it seems the problem originates from the composter inventory reporting as 0-sized when it's full but not bonemeal yet

will keep investigating to identify an appropriate fix

**Comment by TeamDman** [comment]
will get build up soon™

see also: 8b6031c0ec084e25b85f8dc97c8df9995d92f18f lol

**Comment by TeamDman** [comment]
new builds are up
