### ISSUE TITLE
[1.20.1] Updates past 4.14.1 are not marked as Forge so update doesn't show up in app for Forge projects.

### ISSUE THREAD

**Issue by Gbergz** [TeamDman/SuperFactoryManager#117]
Title. [1.20.1]

Currently newer updates are only marked as NeoForge.

![pic](https://github.com/TeamDman/SuperFactoryManager/assets/26634554/5d667882-a81c-401a-825a-0ba2a0a5dd91)

Edit: Not sure if it's intentional or not, reporting to make sure.

**Comment by TeamDman** [comment]
https://github.com/TeamDman/SuperFactoryManager/blob/3c36417fcfe442c7064254191a8c695f8a691616/build.gradle#L275

https://github.com/TeamDman/SuperFactoryManager/blob/7c94ad55d02e61574d543d517536602a1893256b/build.gradle#L276

Technically, Neo is used for 1.20.1+

However, 1.20.1 Neo is compatible with Forge, so I will make sure to list 1.20.1 for both loaders 💃 

Aboutta publish a patch build rn I will mark properly

Will also update release process doc to ensure this is noted
