### ISSUE TITLE
1.20.1 SFM world locking

### ISSUE THREAD

**Issue by funnycubeguy** [TeamDman/SuperFactoryManager#124]
World locks up and spams those threads.

https://pastes.dev/b3UOtdjqOy

Just the basic Factory Manager block with the script 3 inventory cables from SFM and 8 extended inscribers

 every 20 ticks do
    input 64 from barrel
    output 8 EACH to inscriber
END

**Comment by micrwvae** [comment]
this just looks like the server is telling u that sfm is lagging the shit ouf of the server rn

thats because of where u placed the each statement in ur code

rn it works as a whitelist filter
with all items whitelisted
remove the each and see if it gets better

**Comment by TeamDman** [comment]
There are plans to add a warning or to prevent this (EACH without filter) all together

**Comment by funnycubeguy** [comment]
> There are plans to add a warning or to prevent this (EACH without filter) all together

This should be added I disabled sfm for now it breaks servers like that
