### ISSUE TITLE
Crash after inserting a redstone receiver

### ISSUE THREAD

**Issue by ab9rf** [TeamDman/SuperFactoryManager#13]
Server crashed (IndexOutOfBoundsException while ticking block entity) after replacing an inventory cable with a redstone receiver. Server crashed again on restart.

Crash reports are attached.

[crash-2018-12-28_23.16.50-server.txt](https://github.com/TeamDman/SuperFactoryManager/files/2716078/crash-2018-12-28_23.16.50-server.txt)
[crash-2018-12-28_23.19.32-server.txt](https://github.com/TeamDman/SuperFactoryManager/files/2716079/crash-2018-12-28_23.19.32-server.txt)

**Comment by TeamDman** [comment]
Presumably the same issue as #12, should be good now.
