### ISSUE TITLE
Can we have a fork for Quilt or Fabric?

### ISSUE THREAD

**Issue by SoyMidas** [TeamDman/SuperFactoryManager#130]
Is it possible to have a version of this mod for Fabric or Quilt —Quilt preferible, due to those things that Fabric's team had done...—

**Comment by TeamDman** [comment]
SFM relies heavily upon the systems added by forge, I don't have the bandwidth to try this, sorry 😢

**Comment by SoyMidas** [comment]
dw men, your job is so great that I can't be angry.
