### ISSUE TITLE
Severe performance issue

### ISSUE THREAD

**Issue by winterSteve25** [TeamDman/SuperFactoryManager#135]
Hi, I am using SFM to automate the energizing orb in a ftb skies expert playthrough, and I'm encountering severe performance issue when using `output to retain 1 each to output_chest`

here is the sparks profiler result:
![image](https://github.com/TeamDman/SuperFactoryManager/assets/62407972/d52557f0-39e4-4b3a-bbc3-bc4d39910f9d)

I believe it is caused by this line, but I am not certain.
https://github.com/TeamDman/SuperFactoryManager/blob/1.19.2/src/main/java/ca/teamdman/sfml/ast/OutputStatement.java#L295

in the manager interface it says the tick time is around 1000ms.

**Comment by TeamDman** [comment]
using `1 each` is very unoptimized at the moment, it expands for each item in the game right now.
Try restricting it to like `retain 1 each *seed* to output_chest` if you can

**Comment by TeamDman** [comment]
addressed in latest build
