### ISSUE TITLE
Factory Manager forgets lables placed on block even tho the block is still labeled after server restart

### ISSUE THREAD

**Issue by 1matto** [TeamDman/SuperFactoryManager#137]
Playing ATM9 to the sky and found a bug that makes the manager forget labels even tho the blocks are still labeled in the world in version 1.20.1-4.16.0

**Comment by learle868** [comment]
Did you find a fix, I have the same problem on ATM9 to the sky and it is annoying to always re-push the lables to the factory manager.

**Comment by TeamDman** [comment]
I have a fix, just adding some more polish before the next release
