### ISSUE TITLE
[Feature Request] Add support for item name colors

### ISSUE THREAD

**Issue by ThePurityOfChaos** [TeamDman/SuperFactoryManager#139]
For example, Apotheosis has items with orange name colors (&6) which are likely to be more valuable compared to items with purple name colors (&5) but could otherwise appear entirely identical.
A player might want to sort these items into multiple different chests, but currently has no way to differentiate these items. 
The end-user code for a sorter based on item name color might look like this:
every 20 ticks do
    input from inputChest
    output &6 to orangeNameOutputChest
    output &5 to purpleNameOutputChest
end

**Comment by Burkino** [comment]
The name color is based on some NBT data

**Comment by ThePurityOfChaos** [comment]
> The name color is based on some NBT data

Oh, is that already available to parse in SFM?

If so, I'll just close this.

**Comment by ThePurityOfChaos** [comment]
I know, however, that & / §-based color codes can be easily turned into the NBT data through a Style, so it could still be useful to have the &[type] for a more player-friendly access of the data (so long as said player knows that the input matches said data, which is common).

**Comment by ThePurityOfChaos** [comment]
Closing issue as it is essentially a duplicate of https://github.com/TeamDman/SuperFactoryManager/issues/122.
