### ISSUE TITLE
Server startup crash on version 2.0.6 with ClassNotFoundException

### ISSUE THREAD

**Issue by Willsr71** [TeamDman/SuperFactoryManager#14]
On startup the server crashes with version 2.0.6 with the exception `ClassNotFoundException: vswe.superfactory.util.SearchUtil`
Version 2.0.5 works perfectly fine.
 [Crash Report](https://hastebin.com/olenuletih.rb)

**Comment by TeamDman** [comment]
I left some annotations where they shouldn't be, will be fixed with a new build on CF when I close this issue
