### ISSUE TITLE
FeatureRequest: Trashcan ability

### ISSUE THREAD

**Issue by Snow-ctrl-c** [TeamDman/SuperFactoryManager#148]
When making complex factories it would be nice to have a keyword that functions like a trashcan. My keyword suggestions are "void" or "trash"

```
output item:: to void
output fluid:: to trash
```

### productivebees example
when using the [`@productivebees`](https://www.curseforge.com/minecraft/mc-mods/productivebees) mod I often have an excess of wax. It would be convenient to just have to write
```
every 20 ticks do
    input from centrifuges
    output wax to void
    output to storage_system
end
```

**Comment by TeamDman** [comment]
Thanks for the suggestion!
Unfortunately, I think that this is outside the scope of what I want the mod to do at this time.
It's easy enough to use a trash can from another mod or make one yourself using vanilla mechanics and labelling it "trash" or "void" such that your exact example would work.
