### ISSUE TITLE
Mekanism Water Vapor does not get detected?

### ISSUE THREAD

**Issue by kami-tsuki** [TeamDman/SuperFactoryManager#151]
Well short context:
> I am trying to build a Tier 4 Mekansim Ore processor fully automated only taking the ores and returning the ingot then.

While this i need to make Water Vapor (Gas of minecraft made in `Rotary Condensatrator`
Ive connected the Condensentrator to an Inventory cable, from the Manager its receiving water and energy and producing Water Vapor.
The issue seems to be in the extracting, while pressing CTRL + Space on the Label it shows me not that Vapor.

Then i tried to move the Vapor into an Ultimate Tank and trying from there to extract it, but there no side is showing me to extract anything. For Brine it was working.

so while CTRL+SPACE is showing nothing i kinda gess that the SFM is not detecting it.

I am on Neoforge 20.4.237, MC 1.20.4, Mod 4.17.0 and mekanism 10.5.20.41

**Comment by kami-tsuki** [comment]
after a bit more research i figured out that the Resource Type example is not showing the Mekanism Sources as shown in the Tutorial Video, am i missing configs/libaries or anything?

**Comment by TeamDman** [comment]
looks like I forgot to finish porting the mekanism support, it's supported in like 1.19.4 and 1.20.1 but not 1.20.4 yet, will try and get that fixed

**Comment by TeamDman** [comment]
I believe this is fixed in the latest version via e154600ee6e25adae1ff6162bedd5e18d31fba63
