### ISSUE TITLE
Server Crash when using block gate in cable cluster

### ISSUE THREAD

**Issue by Willsr71** [TeamDman/SuperFactoryManager#16]
When using this setup with block gates in cable clusters, the server crashes as long as there are items in the input chest. ![image](https://i.imgur.com/2J4kv0Y.png)

When the server crashed there was a stack of wood and stone in the input chest, however on startup the chest was empty. Not really sure what happened with that one.

[Crash report](https://hastebin.com/apupozesaf.pl)

**Comment by TeamDman** [comment]
It looks like cable cluster crafting is actually broken as well, can you elaborate on how you obtained them in the first place?

**Comment by Willsr71** [comment]
Crafting empty cable clusters and then combining them with another block gets you the cluster with the block
![](https://i.imgur.com/2xS6dKt.png)
![](https://i.imgur.com/vTy4a86.png)
You cannot add any other blocks after creating the cluster, and you cannot create a cluster with regular inventory cable.

**Comment by TeamDman** [comment]
The hastebin expired, but the crash was related to the blockstates not transfering properly between the Cluster facing property and the Blockgate facing property.
There's a lot of duct tape going on right now, but should be working.
