### ISSUE TITLE
Mekanism 1.20.1 Slurry / Chemical Support

### ISSUE THREAD

**Issue by mudgw2** [TeamDman/SuperFactoryManager#178]
Trying to streamline x5 mekanism ore production via slurry and chemical washers using SFM.  The program seems to be setup without errors, yet I'm finding the chemical washers do not interact with the inventory cables.

I am able to get (for example) water to pull from the inventory cables to (for example) and EnderIO fluid tank. So I know there is water in the inventory cables, they however will not fill chemical washers.   

I have the same issue with mekanism chemical tanks not providing slurry to the system. 

Below is the program in use and I will try to provide a screenshot.

```
name "OreWasherFarm1"

every tick do
    input fe:: from power bottom side
    output fe:: to washer
end

every 20 ticks do
    input slurry:: from dirtyslurry
    output slurry:: to washer 
end

every 20 ticks do
    input fluid::water from water
    output fluid::water to washer
end
```
![Screenshot 2024-10-03 091819](https://github.com/user-attachments/assets/d0dc779e-e88b-4035-9797-e8a48527caf9)

Any suggestions or is this simply not supported in SFM?

**Comment by TeamDman** [comment]
Mekanism blocks are read-only when a side isn't specified

Try 

Output slurry:: to washer top side

Also make sure your mek is configs are set

**Comment by mudgw2** [comment]
Excellent, I remember you stating that mekanism needed specific sides in you video, just need practice using it :)  Seems to be pulling everything correctly once thats done.

For the record this is the updated script:
```
name "OreWasherFarm1"

every tick do
    input fe:: from power bottom side
    output fe:: to washer top side
end

every 20 ticks do
    input slurry:: from dirtyslurry east side
    output slurry:: to washer top side
end

every 20 ticks do
    input fluid::water from water
    output fluid::water to washer top side
end
```

**Comment by mudgw2** [comment]
I was a bit quick to close the issue! I was pulling from slurry that was already in the machines and they are working and I thought it was complete when I closed.  However, after the existing slurry cleared out I'm unable to get new slurry in.  The issue seems to be with the Mekanism Chemical Tank which has the Mekanism dirty iron slurry.   In the program posted, its the "dirtyslurry" source.  I have tried defining different sides and doing output everywhere on the chemical tank but SFM dosnt seem to accept either slurry:: or slurry::dirty_iron or other variations.  Any suggestions? on how to get dirty slurry into SFM's system?  

Seems to be the only step remaining on my build.
![Screenshot 2024-10-03 091819](https://github.com/user-attachments/assets/98c11de6-8d48-4b9e-b0c5-768f811ade13)

**Comment by TeamDman** [comment]
In the editor holding Ctrl and hitting space will give some more info depending on what wors the editor cursor is on

**Comment by mudgw2** [comment]
Ok using the Ctrl method I was able to see the values listed and I fully defined my script as below:

```
every 20 ticks do
    input slurry:mekanism:dirty_iron from dirtyslurry east side
    output slurry:mekanism:dirty_iron to washer top side
end
```

No errors, yet I still dont get slurry from the tank (screen shot below, I also tried putting all sides as output)...
![chemcial_tank](https://github.com/user-attachments/assets/028ff2aa-7127-430b-92c7-01dd3f6ce7f3)

**Comment by mudgw2** [comment]
Turns out my washers were only set for INPUT on top and not INPUT/OUTPUT and so things got stuck trying to use only one side of the machine.  Fixed issue by making sure the washers were INPUT/OUTPUT.... sigh :)
