### ISSUE TITLE
Can't access any menu outside of the Factory Manager

### ISSUE THREAD

**Issue by MildFlames** [TeamDman/SuperFactoryManager#186]
Every time I right click on anything, I just get a dark screen. No labels, no buttons, nothing. I'm on 1.21.1 playing the TNP8 modpack, and the developer doesn't know either. I see there are scripts with many custom GUI layers causing it, but my code is extremely basic. Here is my code.
`NAME "Hives"

EVERY 20 TICKS DO
    INPUT FROM hive
    OUTPUT TO drawer
END
`

**Comment by TeamDman** [comment]
there's a problem that is affecting many mods, if you go in to the accessibility settings you can turn blur off which helps I think

**Comment by MildFlames** [comment]
That worked, thanks!

**Comment by TeamDman** [comment]
still an issue, am tracking this in #165
