### ISSUE TITLE
[Bug] multiple redstone recievers in a row not recognized by Manager

### ISSUE THREAD

**Issue by TheonlyTazz** [TeamDman/SuperFactoryManager#19]
![image](https://user-images.githubusercontent.com/3908847/52669054-7bd6bc80-2f15-11e9-9812-7dc8b93ca23b.png)
Trying to hook up multiple recievers in a row but only the first gets recognized

edit: 
yes i know those are redstone emitters, but neither work in a row
![image](https://user-images.githubusercontent.com/3908847/52669335-22bb5880-2f16-11e9-8272-5de3e7dae31d.png)

![image](https://user-images.githubusercontent.com/3908847/52669345-2818a300-2f16-11e9-918d-1e744e4dcb47.png)

**Comment by TeamDman** [comment]
Likely the same as #18

**Comment by TeamDman** [comment]
Any non-basic cable blocks are terminators in a cable chain, the exception being cable clusters, which can be crafted with cables to allow them to carry a signal. The GUI not recognizing the first one is still an issue
