### ISSUE TITLE
The first time you join the game, the connection will time out.

### ISSUE THREAD

**Issue by heiseshuishan** [TeamDman/SuperFactoryManager#22]
I think I have encountered a mistake, he is not very serious, but I want to fix him https://paste.ubuntu.com/p/fMfNQT8jnQ/

**Comment by TeamDman** [comment]
This is caused by SFM caching all the item tooltips (item names and descriptions) so that the search bar doesn't freeze the main thread later (a large item list is probably causing the timeout in this case). Will need to investigate methods to prevent building this cache from taking too long
