### ISSUE TITLE
crash when searching openblock trophies in whitelist

### ISSUE THREAD

**Issue by LocalBoomer** [TeamDman/SuperFactoryManager#25]
https://paste.dimdev.org/igugadorew.mccrash

Title says it all really

smf 2.0.11
forge 14.23.5.2824

**Comment by TeamDman** [comment]
Hastebins expire, reupload on pastebin for posterity
https://pastebin.com/6SpS9qZr

Will investigate

**Comment by TeamDman** [comment]
Everything in the stack trace indicates that the crash occurred when trying to link two nodes together, there's nothing about item search or search results. Do you know what types of components you were trying to link at the time?

**Comment by LocalBoomer** [comment]
I had two inputs and two outputs to move items from a chest to an ME interface and I was adding openblocks' creeper trophie to the second input whitelist. connections were already made so I'm not sure why it says that.

Also ty for the hastebin tip

**Comment by LocalBoomer** [comment]
let me know when the build goes live and I'll see if I can break it again :P

**Comment by TeamDman** [comment]
https://minecraft.curseforge.com/projects/super-factory-manager/files/2696513
Processing now, should go live to that link

**Comment by LocalBoomer** [comment]
No crashing now but the trophies come up blank, (no models just the base) are called 'trophy' not 'mobName trophy' and they aren't being pulled out correctly from the target inventory.

**Comment by TeamDman** [comment]
Might need to set the NBT detection on the filter to fuzzy mode, not too sure about the render issue

**Comment by LocalBoomer** [comment]
Pack I have it in keeps lagging out and I'm too tiresd to figure it out now but will check tomorrow, however, I believe the trophies are all separate items (not just metadata changes) so I don't think fuzzy mode would work however I may be completely wrong :P will will let know my findings.

**Comment by LocalBoomer** [comment]
So I was wrong they are all NBT tagged with the mobs name 🤦‍♂️. Works fine with fuzzy nbt mode so you can mark this fixed. 👍
