### ISSUE TITLE
Buildcraft Facade crash?

### ISSUE THREAD

**Issue by RoloEdits** [TeamDman/SuperFactoryManager#31]
It takes me to the "Connection Lost" Screen after trying to load a world. Im no expert so just ask me if you need anything else :)

its a single player world

version 2.0.14

On a retry to load the world I was able to.
https://pastebin.com/CARnEHBj

**Comment by TeamDman** [comment]
Is this using the latest build? (2.0.14)

**Comment by RoloEdits** [comment]
SuperFactoryManager-1.12.2-2.0.14.jar is what I have installed

**Comment by TeamDman** [comment]
Hm. That's not good, seeing as I added a try-catch to the cache builder on that version. Will look into it

**Comment by TeamDman** [comment]
Can't seem to reproduce. Full mod list?

**Comment by RoloEdits** [comment]
I think i did it right? 

https://pastebin.com/rH7DqwtW

**Comment by RoloEdits** [comment]
I just tested again and got the crash again, is there a place I could post my whole log for you to see? Not sure if that would help

**Comment by RoloEdits** [comment]
Not sure if related, but now It seems to show Tinkers as a problem now. This should be the latest build as of now. SuperFactoryManager-1.12.2-2.0.15.jar

https://pastebin.com/5JxuCQRf
