### ISSUE TITLE
Setting item filtering is hard

### ISSUE THREAD

**Issue by mivalsten** [TeamDman/SuperFactoryManager#32]
Hi,
Could you add better search for allow/deny lists? As of now, when I wanted to allow output of smooth stone, I had to scroll through 2400 items, because for some reason even andesite and all of it's chisel/chisel and bits versions were there.
![image](https://user-images.githubusercontent.com/8068803/58915891-5834bd80-8722-11e9-936f-f567ade0e714.png)
Best regards,
Greg

**Comment by TeamDman** [comment]
There is a `.inv` search selector which might help, but I agree that the search is annoying to work with when decoratives like chisels and facades pollute the item pool. For now I'll look into giving vanilla blocks a higher priority in the search results

**Comment by TeamDman** [comment]
Search improvements implemented!
- Search (still) supports regular expressions
- Search now has 2 mappings per stack, one for just the display name, and one for the combined tooltip 
  - this allows for more intuitive regex anchor usage
- Search now has ordered match results
  - Sort priority, highest to lowest
    - isVanilla
    - lowest difference between display name length and search query length
    - alphabetically


### Regex examples

stone
![image](https://user-images.githubusercontent.com/9356891/58997696-c3869a00-87cb-11e9-88e5-c795b15a8ad0.png)

ends with stone
![image](https://user-images.githubusercontent.com/9356891/58997702-c84b4e00-87cb-11e9-8be3-406ec78b29be.png)

starts with and ends with stone
![image](https://user-images.githubusercontent.com/9356891/58997709-d6996a00-87cb-11e9-882a-ff5e37ea112d.png)


New build also pushed
https://minecraft.curseforge.com/projects/super-factory-manager/files/2720642
