### ISSUE TITLE
CPU spike

### ISSUE THREAD

**Issue by SimonSoby** [TeamDman/SuperFactoryManager#35]
Using the lastest version, when ever i try to crate anything within the inventory manange, i can here my cpu fan start spinning up, and CPU usage sky rises, and if the game survives it will at the end create the trigger in the inventory mananger. But when trying to crate an input the same thing happens

**Comment by SimonSoby** [comment]
Playing on the latest version of FTB Revelation, with a few extra mods added 
![Screenshot_1](https://user-images.githubusercontent.com/25232087/59541139-51673100-8f00-11e9-83d5-05d1e55dbb55.png)

**Comment by TeamDman** [comment]
Presumably, component item lists aren't being rendered lazily. This means that every component with an item picker was calling the search method when you opened the interface.
Making the components lazy is beyond the effort I want to put in for now, so instead I've made the default background search much better.
If there's still performance issues, please let me know!
