### ISSUE TITLE
Creating a Trigger in GUI on server issue

### ISSUE THREAD

**Issue by tgstyle** [TeamDman/SuperFactoryManager#36]
See the Gist from the server log. The Trigger does not show up until exiting and re-opening the GUI. Also cannot create any other commands.

Using 1.12.2-2.0.17

https://gist.github.com/tgstyle/dd746fa343c27a003b95c8f66486195d

**Comment by TeamDman** [comment]
Not too sure what could have caused this. Might be fixed in recent update?

**Comment by tgstyle** [comment]
Latest update has no change. Still cannot create any commands when on a server.
