### ISSUE TITLE
Unable to find GregTech dust in Item filter

### ISSUE THREAD

**Issue by MatthewSmit** [TeamDman/SuperFactoryManager#37]
As in the title, attempting to add any of the gregtech dusts using the item filter fails. Most items seem to be there, but not these ones. I don't believe it's related to #23 as I waited a while for caching to finish after joining the map.

As a workaround, what about being able to select an item from your inventory when selecting item filters, similar to how it works in many other mods (applied energetics 2, extra utilities, ender io, etc).

Modpack: Omnifactory 1.0.5 (with SuperFactoryManager 2.0.17 added manually)
OS: Windows 10 x64
JRE: 1.8.0_211

**Comment by TeamDman** [comment]
Likely an issue with the way gt handles meta item registration. In the mean time, there is already a way to search your inventory using `.inv` as the search.

**Comment by MatthewSmit** [comment]
Just enough items does pick the items up, so presumably there is some difference between how SuperFactoryManager and JEI scan for items.

**Comment by TeamDman** [comment]
Updated search index to just copy JEI's ItemStack list if it's present.
New build up on CurseForge
