### ISSUE TITLE
Server Crash/ World Breaking

### ISSUE THREAD

**Issue by rascalBurritos-zz** [TeamDman/SuperFactoryManager#39]
[crash-2019-07-06_20.01.23-server.txt](https://github.com/TeamDman/SuperFactoryManager/files/3365180/crash-2019-07-06_20.01.23-server.txt)

I attempted to create an input then the server crashed.

**Comment by TeamDman** [comment]
Does this still happen after relaunching and using the latest build?
Latest at this time:
https://www.curseforge.com/minecraft/mc-mods/super-factory-manager/files/2731217
