### ISSUE TITLE
Settings not saved

### ISSUE THREAD

**Issue by Proha5** [TeamDman/SuperFactoryManager#40]
Sorry for bad english.

I set some checkboxes in user preferences.
Reload world. And all checboxes is unchecked.

**Comment by TeamDman** [comment]
Tested in singleplayer on the same world, after creating a new world, and on a server. Each time the settings persisted. Can you give exact steps for reproduction?

**Comment by Proha5** [comment]
I play singleplayer.

My steps:
Open "User preferences" window.
Check "Automaticaly select empty black list" and "Automaticaly select one side for input/output"
Close the game. Run game. Load world. Open preferences. I see, that all checboxes is unchecked.

I open SuperFactoryManagerInside.dat (in config folder)
its contain only 3 bytes:
01 60 00 (HEX)

**Comment by TeamDman** [comment]
Config dir is only specified after proxy init, so it isn't able to find the config. Not sure why I wasn't able to reproduce earlier.

https://github.com/TeamDman/SuperFactoryManager/blob/c894e26f44ffe069fe0ec0d1000b2573d4747fcb/src/main/java/vswe/superfactory/SuperFactoryManager.java#L46-L48

Will comment here once fix is posted.
