### ISSUE TITLE
Weird errors in log

### ISSUE THREAD

**Issue by xJon** [TeamDman/SuperFactoryManager#41]
The mod seems to appear multiple times.
Log: https://pastebin.com/QB6sJDg6
Happened when loading world. In practice I might've timed out.

**Comment by TeamDman** [comment]
Using latest build? 
SFM builds its search index on first world load so the timing of the errors is understandable. In recent builds it should be ignoring them, but worst case scenario it just disconnects you the first time instead of crashing to desktop

**Comment by xJon** [comment]
Yes I was using 2.0.19. The game indeed did not crash but it still might be annoying.

**Comment by xJon** [comment]
Also, upon creating a new world, sometimes the game can time out because of the time it takes to index:
```
[00:17:19] [Thread-67/INFO]: [vswe.superfactory.util.SearchUtil:lambda$buildCache$6:74]: [SFM] Indexed 60986 items in 24504ms.
````
Some times it takes up to 35 seconds.

**Comment by TeamDman** [comment]
The indexing process is performed in a separate thread and shouldn't affect connectivity. If it really is the indexing that's causing problems then I'll probably add a `sleep` call to lighten the performance impact

**Comment by xJon** [comment]
I will do a bit more testing with this big pack I'm using.

**Comment by TeamDman** [comment]
Closing as inactive
