### ISSUE TITLE
Cloning things

### ISSUE THREAD

**Issue by motorist828** [TeamDman/SuperFactoryManager#43]
I found that you can clone things using the IndustrialCraft 2 oven.
Maybe it also works with other machines in a similar way.
Is it possible to expect a fix in modest time?
https://youtu.be/kT3vsPRbdzk

**Comment by TeamDman** [comment]
Things in general have been acting a little wacky with quantity specifiers. Looking into it

**Comment by motorist828** [comment]
bug works with crafting
The bug also appears on the server
Perhaps this is due to other mods.

![Screenshot_37](https://user-images.githubusercontent.com/40582999/61258806-0bf88680-a780-11e9-837d-8d25595a6f3b.png)

https://youtu.be/t7OA6Ib0IkM

**Comment by TeamDman** [comment]
I haven't been able to replicate this using latest (2.0.21) which is now on curseforge. Might have been fixed while fixing other things. If you could confirm that would be much appreciated!
Thanks for the reports!

**Comment by motorist828** [comment]
I tried the new version, the problem remains

**Comment by motorist828** [comment]
I tried the new version, the problem remains

**Comment by motorist828** [comment]
Now I have deleted all the mods, leaving only SFM, the problem is also
I created the world with this error. To get an error, you need to put the boards in the chest
https://drive.google.com/open?id=1U5voS_-xFKTY5rW3aDdSrta7U7sCbgs8
