### ISSUE TITLE
Bug in "For Each Loop" 2

### ISSUE THREAD

**Issue by Proha5** [TeamDman/SuperFactoryManager#44]
the bug present only in v2.0.20.
v2.0.19 was forks fine.

Needs: Move resources to several chests. Using "for loop". (I know, SFM can it do without loop, but my real setup have extended logic)

Input(from source chest, empty black list.)
foreach(List var: Several destination chests; Element var: current)
output(to current, empty black list.)

Run. And SFM fill only 1 chest. Never outputed into other chests.
But, if change code to:
foreach
input
output
then works fine.

**Comment by TeamDman** [comment]
With input empty blacklist
With output whitelist 10xstone
![image](https://user-images.githubusercontent.com/9356891/61584902-f8517500-ab1d-11e9-8d58-a5b1fbd9208d.png)
works
![image](https://user-images.githubusercontent.com/9356891/61584908-08695480-ab1e-11e9-8d46-ec6f81ff56c8.png)
doesn't work (bug)

Should be fixed now, pushing build to Curseforge
