### ISSUE TITLE
Not complete compatible with Ender IO

### ISSUE THREAD

**Issue by UncleSam139** [TeamDman/SuperFactoryManager#46]
If you use the Dimensional Transreceiver from Ender IO you only can send or receive items. It will not work with fluids and that's with a lot of other blocks of this and other mods.

**Comment by desagas** [comment]
Did you have fluid conduits touching the inventory cables? Do you remember?

**Comment by TeamDman** [comment]
Closing since focusing on new version (full rewrite)
