### ISSUE TITLE
Index Out of Bounds Crash

### ISSUE THREAD

**Issue by MasterEnderman** [TeamDman/SuperFactoryManager#48]
SuperFactoryManager: 2.0.21
Forge: 14.23.5.2838
Crash-Report: https://paste.dimdev.org/kotihofexi.mccrash

**Comment by TeamDman** [comment]
Likely a result of numbers shifting when nbt version got bumped. Should be fixed on latest @ curseforge 2.0.22

Best option is to break and replace the offending manager so that the nbt resets
