### ISSUE TITLE
[Suggestion] JEI support akin to enderio

### ISSUE THREAD

**Issue by A-UNDERSCORE-D** [TeamDman/SuperFactoryManager#49]
Enderio filters allow you to click+drag from JEI to add items to filter slots without having to have the item. This would be a decent QOL improvement

**Comment by HenryLoenwind** [comment]
IGhostIngredientHandler, btw. Quite easy to add.

**Comment by TeamDman** [comment]
Would be interesting, hopefully I can get it to play well with the custom gui scaling that SFM uses. Will update here if/when implemented.

**Comment by TeamDman** [comment]
Closing since focusing on new version (full rewrite)
