### ISSUE TITLE
Inventory Cable recipe change request

### ISSUE THREAD

**Issue by Snobux** [TeamDman/SuperFactoryManager#54]
Inventory Cable recipe expensive, in original Steve's Factory Manager you get 8 Inventory Cables, here only 1. Lots of gold (4 ingots) and iron needed per cable, this is limit early game automation, when you need to connect distant things. Can you please make cheaper recipe, at-least as alternative in configs.

**Comment by manaphoenix** [comment]
Not the author, but it is worth noting that this is only a regular crafting recipe and thus can be changed with CraftTweaker. :)

**Comment by Snobux** [comment]
CraftTweaker good for modpack makers. If you play multiplayer modpacks it is not an option. Besides, even in singleplayer modpacks it is tedious to use, modpacks update and it is difficult to maintain your own changes. Finally, it is suggestion to improve mod, that would be beneficial for most/some players. I think, that programming/automation mods like this should not be crafting challenge mods, but instead focus on programming. Besides they very useful, so should be more accessible early in the game.

**Comment by TeamDman** [comment]
Closing since focusing on new version (full rewrite)

**Comment by TeamDman** [comment]
New recipe actually gives 16 I think which might be a bit overtuned, will have to revisit later
