### ISSUE TITLE
High tick usage for getRecipe

### ISSUE THREAD

**Issue by clienthax** [TeamDman/SuperFactoryManager#57]
It seems that getRecipe currently uses a lot of tick time as it is called every crafting operation.
Would it be possible to cache the result of this for a decent speedup, as its unlikely the programs will be changed often?

![image](https://user-images.githubusercontent.com/1056270/70384557-18bc8780-1978-11ea-916e-9198c2d547aa.png)

**Comment by Hachuurui** [comment]
I have noticed this issue as well. We have a single user on our server who setup one SFM setup to make food, and when its active, the server grinds to a halt. When I analyzed it, it was at 615kms. Stopping the SFM from running return the server to normal.

**Comment by TeamDman** [comment]
Closing since focusing on new version (full rewrite)
