### ISSUE TITLE
Can't place triggers or anything other than fluid inputs in the inventory manager, but fluid input freezes game.

### ISSUE THREAD

**Issue by CrimsonVengeance** [TeamDman/SuperFactoryManager#59]
Whenever I attempt to use the inventory manager, I can only place components from fluid input the options under it, and whenever I select a fluid input component, my game freezes permanently. I am on a server running FTB Interactions 1.9.1.

**Comment by CrimsonVengeance** [comment]
The game doesn't always freeze permanently but stays frozen for several minutes, and afterward, creates the components I was originally trying to place, with garbled names.

**Comment by TeamDman** [comment]
Breaking and replacing the manager may solve the issue.
Can you upload a log to pastebin?

**Comment by CrimsonVengeance** [comment]
The game never CTD's just stays frozen, so I have to close the game myself. I don't think there are any logs to upload.

**Comment by TeamDman** [comment]
Closing since focusing on new version (full rewrite)
