### ISSUE TITLE
Cable Clusters with Emitter Forget Emitter

### ISSUE THREAD

**Issue by desagas** [TeamDman/SuperFactoryManager#61]
Emitters in cluster cables disappear, the cluster remains, but the emitter vanishes.

I assume this is very much related to the mismapping issue listed in another issue post.

This can be recreated by doing one of two things, and is a chance, not a guarentee to happen, although extremely likely:
1. Restart the server.
2. Break any cable attached to the network of cables attached to the SFM.

Playing save version as listed in other issue as well.

**Comment by TeamDman** [comment]
Closing since focusing on new version (full rewrite)
