### ISSUE TITLE
Duping when using input/output amount limiting

### ISSUE THREAD

**Issue by algul** [TeamDman/SuperFactoryManager#64]
I can't reproduce this reliably, but it happens a lot. Most often when moving items from inventory and limiting the amount of destination inventory. Sometime SFM can't put stuff into the destination inventory so it tries to put it back, but now it can't (because something else filled the slot for example) so it will start duping by either throwing stacks upon stack on the ground or putting it back, but exceeding the stack limit(going above 64).

**Comment by jmoiron** [comment]
I think this is the same issue as #43

**Comment by TeamDman** [comment]
Closing since focusing on new version (full rewrite)
