### ISSUE TITLE
Machine manager moving wrong quantities of items

### ISSUE THREAD

**Issue by KASEYLINDS** [TeamDman/SuperFactoryManager#66]
I've run into a problem that when trying to automate the assembly of Gregtech tiny piles of dust using the factory manager. I have a buffer inventory that all the tiny piles fill into. I have command sequence "when chest contains (tiny pile) ' item name' specific quantity 9)---- move (tiny pile) ' item name' specific quantity 9) into packager. OR, into adjacent chest, then pipe them into the packager.
The issue seems that when the chest contains a total quantity of 9 tiny piles of ANY type, it will attempt to move the first stack, even if it is not complete. For instance, i have 3 tiny aluminum and 6 tiny sapphire, it will attempt to move both piles into the target inventory, instead of waiting for one stack to reach a total of 9, then moving JUST that stack. Upon messing with it further ive found that if one stack reaches 9, it will also attempt to move all stacks of various dusts, regardless of if any of them have reached the total of 9. When only one dust is listed in the command sequence, it works perfectly. Waits for the stack to reach 9, then moves the stack of 9 into the inventory.
The only solution ive found is to make a separate command sequence for every single dust. I do not want to do that. There are over 200 different dusts. I feel like it should be able to function with all dusts listed in the same sequence. But it confuses the different stacks as part of a total of 9, as opposed to each different dust as its own stack.
 I have found it increasingly frustrating that none of the simple item movement mods have a "move this amount and ONLY this amount" function. I know logistics pipes has this functionality to some degree, but i do not want to set up logistics pipes just for this one process. Im playing FTB interactions BTW

**Comment by TeamDman** [comment]
Closing since focusing on new version (full rewrite)
