### ISSUE TITLE
Ouput(F) set to whitlist specified amount mode fails to block further fluid transmission 

### ISSUE THREAD

**Issue by zjuwyz** [TeamDman/SuperFactoryManager#67]
Mod version: SFM 2.0.24 with FBTI
Step to reproduce
1. build a sfm network with any water tank as input and any block with a fluid slot (i.e., input hatch) from gregtech as output.
2. set output(F) to whitelist mode, use water with 1B specified amount.
3. 1B of water is transfered each time sfm is triggered, without checking the amount of water of the output side.

Froster from industrial foregoing also has this issue so this shouldn' be related to gregtech itself.

**Comment by TeamDman** [comment]
Fluid interfaces that only accept fluid but cannot be withdrawn from will likely show as being empty to SFM. 
In future will maybe try and have custom mod support to peek inside the hidden inventories for conditionals to work closer to expectations

**Comment by zjuwyz** [comment]
Thank you for your reply.  @TeamDman 

I tried some other methods to interact between sfm and gregtech machines, and the result is getting weird...

1. Input fluid slot is not working well with whitlist specified amount, as described above.
2. However, condition(F) works just fine with input fluid slot, and so does output(F) advanced mode, indicating that sfm is technically accessible to the input fluid slot.
3. Input items slot seems invisible for item detectors, condition commands always return false.
4. However, output command set to whitelist of specified amount works just fine, indicating that sfm itself can somehow see what's in the input slots.
5. Both item and fluid output slots seems working properly. I didn't find any issue related with them.

So... those slots which cannot be withdrawn from is not completely unaccessable, but they are buggy in different ways...which is really painful when building a gregtech automation...

**Comment by TeamDman** [comment]
Closing since focusing on new version (full rewrite)
