### ISSUE TITLE
Diamond block generator

### ISSUE THREAD

**Issue by jeremiahwinsley** [TeamDman/SuperFactoryManager#70]
Currently this works as a diamond block generator on 1.18. I assume that's just testing code that got left in accidentally.

https://github.com/TeamDman/SuperFactoryManager/blob/813e9aa8fdeed29d1760e5904232b48b78899f3d/src/main/java/ca/teamdman/sfm/common/blockentity/ManagerBlockEntity.java#L62

**Comment by TeamDman** [comment]
Correct, fixed in d70738994d9715e234c19fc2767aa41037fa507e and a new build is available on CurseForge
Thank you!
