### ISSUE TITLE
Crash using Redstone Trigger

### ISSUE THREAD

**Issue by phit** [TeamDman/SuperFactoryManager#76]
not sure if this is supposed to be implemented yet

https://gist.github.com/phit/a0a6cab5b3924ab23a4155c09afbef51

**Comment by TeamDman** [comment]
Not implemented yet, but crashing is also very not-good. I'll look into it.
Thanks for the heads up!

**Comment by TeamDman** [comment]
I implemented a basic version of redstone trigger and conditional logic.
The original SFM had a separate block that could be used, but for now this should be good. Apply signal to manager block as you would a dispenser.
https://www.curseforge.com/minecraft/mc-mods/super-factory-manager/files/3843281

see https://github.com/TeamDman/SuperFactoryManager/blob/1.19/examples/07-redstone.sfm for example usage

**Comment by phit** [comment]
very nice, thank you! will check it out soon

**Comment by closet-raccoon** [comment]
Hey can you fix this in 1.18.2 as well? It causes the region to be corrupted, and I would love to use redstone triggers.

**Comment by TeamDman** [comment]
There's a forge option to remove erroring entities that can help in the mean time, I'll see how hard it is to backport when I have time

https://www.reddit.com/r/feedthebeast/comments/4813rh/removing_erroring_tile_entities/d0grah6/
