### ISSUE TITLE
Redstone Receiver Broken

### ISSUE THREAD

**Issue by fantasigible001** [TeamDman/SuperFactoryManager#8]
Placing a lever or pressure plate near the Redstone Receiver that is connected to the main controller block (I forgot the name, sorry) will work normally, but sometimes the lever that is in my inv(creative mode) disappears and right clicking the lever or stepping on the pressure plate will take longer time to trigger, as if it's lagging. Sometimes while i do it the game crashes.

The Main Controller Block program :
Trigger > Redstone Controller > Connectors (Redstone Receiver)

**Comment by TeamDman** [comment]
Could not reproduce.
Please provide screenshots of both the in world cabling and the manager gui.

My working setup
![image](https://user-images.githubusercontent.com/9356891/49672545-81a5b280-fa39-11e8-800a-74fb8299a355.png)
![image](https://user-images.githubusercontent.com/9356891/49672620-b580d800-fa39-11e8-8aaa-d6564031fc18.png)
