### ISSUE TITLE
Drawers and factory manager overfilling (bug)

### ISSUE THREAD

**Issue by larskr96** [TeamDman/SuperFactoryManager#9]
The manager moves items to the drawer even if the drawer is full

**Comment by larskr96** [comment]
1 more thing it voids every single other item that you take in to the Storage drawer With it

**Comment by TeamDman** [comment]
Looks like StorageDrawers operate using a virtual itemslot to as a buffer between its 'real' inventory and the 'normal' inventory that minecraft operates with, most likely missed some slot item insertion validity checks when adapting SFM to use capabilities. Fix should be reasonably straightforward.
