### ISSUE TITLE
Better error message for used keywords

### ISSUE THREAD

**Issue by Knito58** [TeamDman/SuperFactoryManager#92]
The error message when you try to move minecraft:redstone from here to there is rather cryptic. It is not obvious that you have to put "redstone" in quotes. The error message should alert me about the fact and propose quoting the string.

**Comment by TeamDman** [comment]
fixed in 4.14.0

-- fix REDSTONE keyword not being allowed as a resource id
---- INPUT redstone FROM a -- works now :D

this fix is explicitly for the word "redstone", the error message is unchanged but people should encounter it much less often given the minimal overlap of keywords vs item names
