### ISSUE TITLE
Dedicated server crash

### ISSUE THREAD

**Issue by HarroldCodes** [TeamDman/SuperFactoryManager#95]
Dedicated server crash after placing the Factory Manager and loading it with a program then restarting the server.
Server crash log:  [crash-2023-04-17_17.44.35-server.txt](https://github.com/TeamDman/SuperFactoryManager/files/11246594/crash-2023-04-17_17.44.35-server.txt)
The Factory Manager is interacting with a vanilla chest & an Energizing Orb from "Powah!"

**Comment by TeamDman** [comment]
Thanks for the report!
Should be fixed in v4.7.2, which is being approved on curseforge right now
